import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  globalContainer: {
    marginHorizontal: 20,
  },
  mainContainer: {
    backgroundColor: '#FFFFFF',
    height: 350,
    borderRadius: 15,
    paddingHorizontal: 10,
    paddingVertical: 20,
  },
  h1: {
    color: '#020202',
    fontSize: 16,
  },
  h2: {
    marginBottom: 20,
    color: '#9B9898',
    fontSize: 14,
    fontWeight: '800',
    fontFamily: 'AvenirLTStd-Black',
  },
  pointsCard: {
    backgroundColor: '#334FFA',
    padding: 25,
    marginHorizontal: 20,
    borderRadius: 20,
    height: 160,
    shadowColor: 'rgba(0, 0, 0, 0.5)',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.9,
    shadowRadius: 8.3,
    elevation: 13,
  },
  titleCard: {
    color: '#FFFFFF',
    marginBottom: 10,
    fontSize: 16,
    fontWeight: '800',
    fontFamily: 'AvenirLTStd-Black',
  },
  numberPoints: {
    color: '#FFFFFF',
    fontFamily: 'AvenirLTStd-Black',
    fontWeight: '800',
    fontSize: 32,
  },
  rowBtns: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    marginTop: 10,
  },
  containerBtn: {
    backgroundColor: '#334FFA',
    width: 170,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  textBtn: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    fontFamily: 'AvenirLTStd-Black',
  },
  allBtn: {
    marginTop: 20,
    backgroundColor: '#334FFA',
    width: '100%',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  textAllBtn: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
    fontFamily: 'AvenirLTStd-Black',
  },
  detailPage: {
    width: '100%',
    height: 150,
    backgroundColor: '#CFD6FF',
    paddingVertical: 20,
    paddingHorizontal: 10,
    justifyContent: 'flex-end',
  },
  titleProduct: {
    fontWeight: '800',
    fontSize: 24,
    fontFamily: 'AvenirLTStd-Black',
    color: '#000000',
  },
  containerDetail: {
    width: 350,
    height: 350,
    marginTop: 20,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.39,
    shadowRadius: 8.3,
    elevation: 13,
  },
  subText: {
    color: '#9B9898',
    fontFamily: 'AvenirLTStd-Black',
    fontWeight: '800',
    fontSize: 14,
    marginBottom: 10,
  },
  exactp: {
    color: '#9B9898',
    fontFamily: 'AvenirLTStd-Black',
    fontWeight: '800',
    fontSize: 14,
    marginBottom: 10,
  },
});
